### PR TITLE
Fixed URL regex

### LINKED ISSUE #1: URL Regex broken
Hi @ThePoShWolf 

I have the following case which throws an error:

```powershell
$CurlCommand = @"
curl -X GET \
https://PlopServer/identity/api/tenants/Woopa/subtenants \
-H 'Accept: application/json' \
-H 'Authorization: Bearer {{token}}'
"@

ConvertTo-IRM -CurlString $CurlCommand
```

this is the error I get:

image

I actually think have fixed the regex already (on line 13). 

The second thing that is a bit disturbing is the 'False' that we can see right above the `invoke-restMethod` output.

I'll push a PR with the regex fix shortly

Cheers

### PR DESCRIPTION
**Pull request by Stephanevg**
Salutation!

Fixed #1 

The regex was built in a way, that if you had an url without .XXX, it would not correctly parse the string.
I also added a pester test with 2 test cases.

Another thing that poped into my mind, is how do you want to handle wrong urls. Like: http:/// for example? Throw an error, or simply return $null? (I have pre-prepared a pester test for that too).

I also added a (very) short comment based help. As this is not (yet?) a module, there was no 'versioning'. You can see I added a version in the .NOTES section of the comment based help.

Cheers

ps: You only have the master branch, so I couldn't do the PR to a dev branch.

### CODE REVIEW

**Comment by ThePoShWolf** [comment]
@Stephanevg Thank you for taking the time! You are correct, this isn't a module as I haven't yet made the effort for a single cmdlet.

And indeed, there are a lot of edge cases that this doesn't account for yet! So if it doesn't find an appropriate url, it will have to throw an error. 'Could not find a valid url' or something.

One thing I noticed is that you are using ```^``` to start the regex, the url won't be at the start of ```$CurlString``` as ```curl``` should be at the start of it. That should be removed.

Great catch by the way, thanks for the addition and the help and pester test.

**Comment by Stephanevg** [comment]
As discussed, I removed the '^' :)

>What is 'strange' is that my tests passed with AND without that sign. 
If it is present or not, the query actually still returns the query I was expecting. 
This is prob also something to test further.

**Comment by ThePoShWolf** [comment]
@Stephanevg I believe that is related to #5 . My intention of matching the URI was to remove it from ```$workingStr``` (line 31 in your repo) and then add it to ```$outString```. The only problem is that I forgot to add it to ```$outString```.

What I'm guessing is that the url matching isn't actually working since it isn't getting removed from ```$workingStr``` on line 31 and is instead being included in the first matched parameter since it still is included in ```$outString```.

Taking a closer look at the regex, it looks like there is a ```|``` that should be ```?``` on line 27:

```PowerShell
$CurlString -match 'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=\/]{2,256}(\.[a-z]{2,6}\b)|([-a-zA-Z0-9@:%_\+.~#?&\/\/=,]*)'
```

Should be:

```PowerShell
$CurlString -match 'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=\/]{2,256}(\.[a-z]{2,6}\b)?([-a-zA-Z0-9@:%_\+.~#?&\/\/=,]*)'
```

Otherwise it actually matches ```curl``` from that string. One thing you will notice, due to #5 , is that the URL will not be output, that is a known issue and I'll actually be streaming some more work on this tomorrow 😄 

 I would make that quick update myself, but I'm not sure how to edit a PR before merging.

**Comment by ThePoShWolf** [comment]
Also, every time I work with regex, I always think of this:
regex problems

Replace ```Perl``` with ```PowerShell``` though 😆

**Comment by Stephanevg** [comment]
haha, $true about the regex thing.
but you know what, over time, I some how started to love regex. (Yeah, pretty weird huh ;)) 

I actually love it so much, that I was looking in to resolving the conflicts on this Pr, and realized I could write a nice function to simplify a bit some of the things in the `ConvertTo-IRM` function.

So in my latest commit you will find the addition of one file in the functions folder. It contains a function called `Get-URLData`. Currently, it is not in use in the `ConvertTo-IRM` function. But I have added a short example on line 32

```powershell
$UrlData = Get-URLData -Url $CurlString 
```

It will return a nice (and confortable) object containing all the details of a WebURL. 

For example, we could something like this:

Instead of this:

```powershell
$workingStr = $CurlString -replace '^curl\s+','' -replace "['`"]?$escapedUrl['`"]?",''
```
we could do

```powershell
$UrlData = Get-URLData -Url $CurlString
$workingStr = $UrlData.FullUrl
``` 
I'll let you implement it (if you feel like it) :)

> Get-URLData uses a ordered hashtable. this means that the function will not work on systems with a lower version as PowerShell v3. If this is not an acceptable solution for you, we could potentially just remove the `[Ordered]` keyword from the function. It will work the same, just the values will be in different order.

**Comment by ThePoShWolf** [comment]
Yeah, regex is amazing once you get it figured out, which is why I'm using extensively in this module.

That Get-URLData cmdlet is brilliant. Makes me think I should also split out the parameter parsing 🤔

Anyways, this is awesome. Thank you very much for taking the time!

**Pull request merged**
